// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: cosmos/evm/valrewards/v1/valrewards.proto

package types

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params defines the valrewards module parameters.
type Params struct {
	// whitelist are the addresses allowed to stage runtime reward-setting updates.
	Whitelist []string `protobuf:"bytes,1,rep,name=whitelist,proto3" json:"whitelist,omitempty"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_aba4a89507aa464b, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetWhitelist() []string {
	if m != nil {
		return m.Whitelist
	}
	return nil
}

// RewardSettings defines the reward settings applied by epoch.
type RewardSettings struct {
	// blocks_in_epoch is the number of blocks in an epoch.
	BlocksInEpoch int64 `protobuf:"varint,1,opt,name=blocks_in_epoch,json=blocksInEpoch,proto3" json:"blocks_in_epoch,omitempty"`
	// rewards_per_epoch is the total reward amount distributed for an epoch, in decimal string form.
	RewardsPerEpoch string `protobuf:"bytes,2,opt,name=rewards_per_epoch,json=rewardsPerEpoch,proto3" json:"rewards_per_epoch,omitempty"`
	// rewarding_paused disables point accumulation and reward row creation for the epoch when true.
	RewardingPaused bool `protobuf:"varint,3,opt,name=rewarding_paused,json=rewardingPaused,proto3" json:"rewarding_paused,omitempty"`
}

func (m *RewardSettings) Reset()         { *m = RewardSettings{} }
func (m *RewardSettings) String() string { return proto.CompactTextString(m) }
func (*RewardSettings) ProtoMessage()    {}
func (*RewardSettings) Descriptor() ([]byte, []int) {
	return fileDescriptor_aba4a89507aa464b, []int{1}
}
func (m *RewardSettings) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RewardSettings) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RewardSettings.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RewardSettings) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RewardSettings.Merge(m, src)
}
func (m *RewardSettings) XXX_Size() int {
	return m.Size()
}
func (m *RewardSettings) XXX_DiscardUnknown() {
	xxx_messageInfo_RewardSettings.DiscardUnknown(m)
}

var xxx_messageInfo_RewardSettings proto.InternalMessageInfo

func (m *RewardSettings) GetBlocksInEpoch() int64 {
	if m != nil {
		return m.BlocksInEpoch
	}
	return 0
}

func (m *RewardSettings) GetRewardsPerEpoch() string {
	if m != nil {
		return m.RewardsPerEpoch
	}
	return ""
}

func (m *RewardSettings) GetRewardingPaused() bool {
	if m != nil {
		return m.RewardingPaused
	}
	return false
}

// EpochState defines the explicit epoch-tracking state stored by the module.
type EpochState struct {
	// current_epoch is the epoch currently collecting points.
	CurrentEpoch uint64 `protobuf:"varint,1,opt,name=current_epoch,json=currentEpoch,proto3" json:"current_epoch,omitempty"`
	// blocks_into_current_epoch is the number of committed blocks already counted in current_epoch.
	BlocksIntoCurrentEpoch int64 `protobuf:"varint,2,opt,name=blocks_into_current_epoch,json=blocksIntoCurrentEpoch,proto3" json:"blocks_into_current_epoch,omitempty"`
}

func (m *EpochState) Reset()         { *m = EpochState{} }
func (m *EpochState) String() string { return proto.CompactTextString(m) }
func (*EpochState) ProtoMessage()    {}
func (*EpochState) Descriptor() ([]byte, []int) {
	return fileDescriptor_aba4a89507aa464b, []int{2}
}
func (m *EpochState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EpochState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EpochState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EpochState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EpochState.Merge(m, src)
}
func (m *EpochState) XXX_Size() int {
	return m.Size()
}
func (m *EpochState) XXX_DiscardUnknown() {
	xxx_messageInfo_EpochState.DiscardUnknown(m)
}

var xxx_messageInfo_EpochState proto.InternalMessageInfo

func (m *EpochState) GetCurrentEpoch() uint64 {
	if m != nil {
		return m.CurrentEpoch
	}
	return 0
}

func (m *EpochState) GetBlocksIntoCurrentEpoch() int64 {
	if m != nil {
		return m.BlocksIntoCurrentEpoch
	}
	return 0
}

func init() {
	proto.RegisterType((*Params)(nil), "cosmos.evm.valrewards.v1.Params")
	proto.RegisterType((*RewardSettings)(nil), "cosmos.evm.valrewards.v1.RewardSettings")
	proto.RegisterType((*EpochState)(nil), "cosmos.evm.valrewards.v1.EpochState")
}

func init() {
	proto.RegisterFile("cosmos/evm/valrewards/v1/valrewards.proto", fileDescriptor_aba4a89507aa464b)
}

var fileDescriptor_aba4a89507aa464b = []byte{
	// 308 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x91, 0x31, 0x4b, 0xc3, 0x40,
	0x1c, 0xc5, 0x7b, 0xad, 0x14, 0x7b, 0x58, 0xab, 0x19, 0x24, 0x82, 0x1c, 0xa1, 0x42, 0x49, 0x1d,
	0x12, 0x8a, 0x93, 0x6b, 0xc5, 0xc1, 0xad, 0xa4, 0x9b, 0x4b, 0xb8, 0xa6, 0x7f, 0xd2, 0xc3, 0xe4,
	0x2e, 0xdc, 0xfd, 0x9b, 0xea, 0xa7, 0xd0, 0x8f, 0xe5, 0xd8, 0xd1, 0x51, 0xda, 0x2f, 0x22, 0x26,
	0xa9, 0x9e, 0xe3, 0xfd, 0xde, 0x7b, 0xf7, 0x7f, 0xf0, 0xe8, 0x38, 0x51, 0x26, 0x57, 0x26, 0x84,
	0x32, 0x0f, 0x4b, 0x9e, 0x69, 0xd8, 0x70, 0xbd, 0x34, 0x61, 0x39, 0xb1, 0x5e, 0x41, 0xa1, 0x15,
	0x2a, 0xc7, 0xad, 0xad, 0x01, 0x94, 0x79, 0x60, 0x89, 0xe5, 0x64, 0x38, 0xa2, 0xdd, 0x19, 0xd7,
	0x3c, 0x37, 0xce, 0x15, 0xed, 0x6d, 0x56, 0x02, 0x21, 0x13, 0x06, 0x5d, 0xe2, 0x75, 0xfc, 0x5e,
	0xf4, 0x07, 0x86, 0x6f, 0x84, 0x9e, 0x46, 0x55, 0x6c, 0x0e, 0x88, 0x42, 0xa6, 0xc6, 0x19, 0xd1,
	0xc1, 0x22, 0x53, 0xc9, 0xb3, 0x89, 0x85, 0x8c, 0xa1, 0x50, 0xc9, 0xca, 0x25, 0x1e, 0xf1, 0x3b,
	0x51, 0xbf, 0xc6, 0x8f, 0xf2, 0xe1, 0x07, 0x3a, 0x37, 0xf4, 0xbc, 0x39, 0x18, 0x17, 0xa0, 0x1b,
	0x67, 0xdb, 0x23, 0x7e, 0x2f, 0x1a, 0x34, 0xc2, 0x0c, 0x74, 0xed, 0x1d, 0xd3, 0xb3, 0x1a, 0x09,
	0x99, 0xc6, 0x05, 0x5f, 0x1b, 0x58, 0xba, 0x1d, 0x8f, 0xf8, 0xc7, 0x07, 0xab, 0x90, 0xe9, 0xac,
	0xc2, 0xc3, 0x8c, 0xd2, 0x2a, 0x33, 0x47, 0x8e, 0xe0, 0x5c, 0xd3, 0x7e, 0xb2, 0xd6, 0x1a, 0x24,
	0x5a, 0x55, 0x8e, 0xa2, 0x93, 0x06, 0xd6, 0xbf, 0xdf, 0xd1, 0xcb, 0xdf, 0xc6, 0xa8, 0xe2, 0xff,
	0x81, 0x76, 0xd5, 0xfd, 0xe2, 0xd0, 0x1d, 0xd5, 0xbd, 0x15, 0x9d, 0x4e, 0x3f, 0x76, 0x8c, 0x6c,
	0x77, 0x8c, 0x7c, 0xed, 0x18, 0x79, 0xdf, 0xb3, 0xd6, 0x76, 0xcf, 0x5a, 0x9f, 0x7b, 0xd6, 0x7a,
	0xf2, 0x53, 0x81, 0xab, 0xf5, 0x22, 0x48, 0x54, 0x1e, 0x5a, 0x8b, 0xbc, 0xd8, 0x9b, 0xe0, 0x6b,
	0x01, 0x66, 0xd1, 0xad, 0xc6, 0xb8, 0xfd, 0x0e, 0x00, 0x00, 0xff, 0xff, 0x72, 0x77, 0x8c, 0x08,
	0xb9, 0x01, 0x00, 0x00,
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Whitelist) > 0 {
		for iNdEx := len(m.Whitelist) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Whitelist[iNdEx])
			copy(dAtA[i:], m.Whitelist[iNdEx])
			i = encodeVarintValrewards(dAtA, i, uint64(len(m.Whitelist[iNdEx])))
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *RewardSettings) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RewardSettings) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RewardSettings) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.RewardingPaused {
		i--
		if m.RewardingPaused {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x18
	}
	if len(m.RewardsPerEpoch) > 0 {
		i -= len(m.RewardsPerEpoch)
		copy(dAtA[i:], m.RewardsPerEpoch)
		i = encodeVarintValrewards(dAtA, i, uint64(len(m.RewardsPerEpoch)))
		i--
		dAtA[i] = 0x12
	}
	if m.BlocksInEpoch != 0 {
		i = encodeVarintValrewards(dAtA, i, uint64(m.BlocksInEpoch))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *EpochState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EpochState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EpochState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.BlocksIntoCurrentEpoch != 0 {
		i = encodeVarintValrewards(dAtA, i, uint64(m.BlocksIntoCurrentEpoch))
		i--
		dAtA[i] = 0x10
	}
	if m.CurrentEpoch != 0 {
		i = encodeVarintValrewards(dAtA, i, uint64(m.CurrentEpoch))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintValrewards(dAtA []byte, offset int, v uint64) int {
	offset -= sovValrewards(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Whitelist) > 0 {
		for _, s := range m.Whitelist {
			l = len(s)
			n += 1 + l + sovValrewards(uint64(l))
		}
	}
	return n
}

func (m *RewardSettings) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.BlocksInEpoch != 0 {
		n += 1 + sovValrewards(uint64(m.BlocksInEpoch))
	}
	l = len(m.RewardsPerEpoch)
	if l > 0 {
		n += 1 + l + sovValrewards(uint64(l))
	}
	if m.RewardingPaused {
		n += 2
	}
	return n
}

func (m *EpochState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.CurrentEpoch != 0 {
		n += 1 + sovValrewards(uint64(m.CurrentEpoch))
	}
	if m.BlocksIntoCurrentEpoch != 0 {
		n += 1 + sovValrewards(uint64(m.BlocksIntoCurrentEpoch))
	}
	return n
}

func sovValrewards(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozValrewards(x uint64) (n int) {
	return sovValrewards(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowValrewards
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Whitelist", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowValrewards
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthValrewards
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthValrewards
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Whitelist = append(m.Whitelist, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipValrewards(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthValrewards
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RewardSettings) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowValrewards
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RewardSettings: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RewardSettings: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlocksInEpoch", wireType)
			}
			m.BlocksInEpoch = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowValrewards
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BlocksInEpoch |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RewardsPerEpoch", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowValrewards
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthValrewards
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthValrewards
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RewardsPerEpoch = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RewardingPaused", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowValrewards
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.RewardingPaused = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipValrewards(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthValrewards
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EpochState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowValrewards
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EpochState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EpochState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CurrentEpoch", wireType)
			}
			m.CurrentEpoch = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowValrewards
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CurrentEpoch |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlocksIntoCurrentEpoch", wireType)
			}
			m.BlocksIntoCurrentEpoch = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowValrewards
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BlocksIntoCurrentEpoch |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipValrewards(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthValrewards
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipValrewards(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowValrewards
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowValrewards
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowValrewards
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthValrewards
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupValrewards
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthValrewards
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthValrewards        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowValrewards          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupValrewards = fmt.Errorf("proto: unexpected end of group")
)
