.PHONY: help
help:
	@echo "Targets:"
	@echo "  build           Build ctmd (dev) + Rust lib"
	@echo "  lint-go         Run golangci-lint plus the halt/B5 policy checks"
	@echo "  lint-halt       Fail on unreviewed panic() calls in consensus-adjacent paths"
	@echo "  lint-b5         Fail on unreviewed repair/sanitize/unsafe risk markers"
	@echo "  dist            Build a self-contained bundle in build/dist"
	@echo "  verify-dist     Validate the dist bundle layout"
	@echo "  package-dist    Create a release tarball under ./dist"
	@echo "  install         Install into BINDIR (+ Frameworks/ or lib/ bundle)"
	@echo "  install-system  (Linux) install Rust lib into /usr/local/lib (sudo required)"
	@echo "  vendor          Vendor Go + Rust dependencies locally"
	@echo "  vendor-clean    Remove vendored dependency directories"
	@echo "  reproducibility-env  Print JSON toolchain fingerprint"
	@echo "  test fmt vet tidy mod-download clean doctor"
	@echo ""
	@echo "Common overrides:"
	@echo "  ROCKSDB_ENABLED=true|false, ROCKSDB_REQUIRED=true"
	@echo "  ROCKSDB_PREFIX=..., PKG_CONFIG=..."
	@echo "  RUSTUP_TOOLCHAIN=..., RUST_SP1_PROFILE=release|dev"
	@echo "  RUST_SP1_LOCKED=true, RUST_SP1_FROZEN=true"
	@echo "  GOFLAGS=..., BINDIR=..., BUILDDIR=..., RELEASEDIR=..."
	@echo "  ASSET_BASENAME=ctmd-<version>-<os>-<arch>"
