// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: cosmos/evm/circuit/v1/query.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QuerySystemAvailableRequest defines the request type for Query/SystemAvailable.
type QuerySystemAvailableRequest struct {
}

func (m *QuerySystemAvailableRequest) Reset()         { *m = QuerySystemAvailableRequest{} }
func (m *QuerySystemAvailableRequest) String() string { return proto.CompactTextString(m) }
func (*QuerySystemAvailableRequest) ProtoMessage()    {}
func (*QuerySystemAvailableRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d94f72004e6d31d, []int{0}
}
func (m *QuerySystemAvailableRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QuerySystemAvailableRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QuerySystemAvailableRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QuerySystemAvailableRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuerySystemAvailableRequest.Merge(m, src)
}
func (m *QuerySystemAvailableRequest) XXX_Size() int {
	return m.Size()
}
func (m *QuerySystemAvailableRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QuerySystemAvailableRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QuerySystemAvailableRequest proto.InternalMessageInfo

// QuerySystemAvailableResponse defines the response type for Query/SystemAvailable.
type QuerySystemAvailableResponse struct {
	// system_available is the current system availability flag.
	SystemAvailable bool `protobuf:"varint,1,opt,name=system_available,json=systemAvailable,proto3" json:"system_available,omitempty"`
}

func (m *QuerySystemAvailableResponse) Reset()         { *m = QuerySystemAvailableResponse{} }
func (m *QuerySystemAvailableResponse) String() string { return proto.CompactTextString(m) }
func (*QuerySystemAvailableResponse) ProtoMessage()    {}
func (*QuerySystemAvailableResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d94f72004e6d31d, []int{1}
}
func (m *QuerySystemAvailableResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QuerySystemAvailableResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QuerySystemAvailableResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QuerySystemAvailableResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuerySystemAvailableResponse.Merge(m, src)
}
func (m *QuerySystemAvailableResponse) XXX_Size() int {
	return m.Size()
}
func (m *QuerySystemAvailableResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QuerySystemAvailableResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QuerySystemAvailableResponse proto.InternalMessageInfo

// QueryWhitelistRequest defines the request type for Query/Whitelist.
type QueryWhitelistRequest struct {
}

func (m *QueryWhitelistRequest) Reset()         { *m = QueryWhitelistRequest{} }
func (m *QueryWhitelistRequest) String() string { return proto.CompactTextString(m) }
func (*QueryWhitelistRequest) ProtoMessage()    {}
func (*QueryWhitelistRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d94f72004e6d31d, []int{2}
}
func (m *QueryWhitelistRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryWhitelistRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryWhitelistRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryWhitelistRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryWhitelistRequest.Merge(m, src)
}
func (m *QueryWhitelistRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryWhitelistRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryWhitelistRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryWhitelistRequest proto.InternalMessageInfo

// QueryWhitelistResponse defines the response type for Query/Whitelist.
type QueryWhitelistResponse struct {
	// whitelist is the list of authorized addresses.
	Whitelist []string `protobuf:"bytes,1,rep,name=whitelist,proto3" json:"whitelist,omitempty"`
}

func (m *QueryWhitelistResponse) Reset()         { *m = QueryWhitelistResponse{} }
func (m *QueryWhitelistResponse) String() string { return proto.CompactTextString(m) }
func (*QueryWhitelistResponse) ProtoMessage()    {}
func (*QueryWhitelistResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d94f72004e6d31d, []int{3}
}
func (m *QueryWhitelistResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryWhitelistResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryWhitelistResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryWhitelistResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryWhitelistResponse.Merge(m, src)
}
func (m *QueryWhitelistResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryWhitelistResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryWhitelistResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryWhitelistResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*QuerySystemAvailableRequest)(nil), "cosmos.evm.circuit.v1.QuerySystemAvailableRequest")
	proto.RegisterType((*QuerySystemAvailableResponse)(nil), "cosmos.evm.circuit.v1.QuerySystemAvailableResponse")
	proto.RegisterType((*QueryWhitelistRequest)(nil), "cosmos.evm.circuit.v1.QueryWhitelistRequest")
	proto.RegisterType((*QueryWhitelistResponse)(nil), "cosmos.evm.circuit.v1.QueryWhitelistResponse")
}

func init() { proto.RegisterFile("cosmos/evm/circuit/v1/query.proto", fileDescriptor_3d94f72004e6d31d) }

var fileDescriptor_3d94f72004e6d31d = []byte{
	// 352 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x52, 0xcd, 0x4a, 0xf3, 0x40,
	0x14, 0xcd, 0xf4, 0xe3, 0x13, 0x3b, 0x9b, 0xca, 0x60, 0xb5, 0xc4, 0x3a, 0xd4, 0x80, 0xd8, 0x82,
	0xce, 0xd0, 0x16, 0xdc, 0xab, 0x2b, 0x97, 0xd6, 0x85, 0xe0, 0x46, 0xd2, 0x30, 0xa4, 0x03, 0x49,
	0x6e, 0xda, 0x99, 0x44, 0xbb, 0xf5, 0x09, 0x44, 0x1f, 0xc3, 0x17, 0x29, 0xae, 0x0a, 0x6e, 0x5c,
	0x6a, 0xeb, 0x83, 0x48, 0x93, 0xb6, 0x6a, 0xa8, 0x45, 0x77, 0xe1, 0x9e, 0x9f, 0x7b, 0xee, 0xc9,
	0xe0, 0x1d, 0x07, 0x94, 0x0f, 0x8a, 0x8b, 0xd8, 0xe7, 0x8e, 0xec, 0x39, 0x91, 0xd4, 0x3c, 0xae,
	0xf3, 0x6e, 0x24, 0x7a, 0x7d, 0x16, 0xf6, 0x40, 0x03, 0x29, 0xa6, 0x14, 0x26, 0x62, 0x9f, 0x4d,
	0x29, 0x2c, 0xae, 0x9b, 0xeb, 0x2e, 0xb8, 0x90, 0x30, 0xf8, 0xe4, 0x2b, 0x25, 0x9b, 0x65, 0x17,
	0xc0, 0xf5, 0x04, 0xb7, 0x43, 0xc9, 0xed, 0x20, 0x00, 0x6d, 0x6b, 0x09, 0x81, 0x4a, 0x51, 0x6b,
	0x1b, 0x6f, 0x9d, 0x4d, 0x9c, 0xcf, 0xfb, 0x4a, 0x0b, 0xff, 0x28, 0xb6, 0xa5, 0x67, 0xb7, 0x3d,
	0xd1, 0x12, 0xdd, 0x48, 0x28, 0x6d, 0x9d, 0xe2, 0xf2, 0x62, 0x58, 0x85, 0x10, 0x28, 0x41, 0x6a,
	0x78, 0x4d, 0x25, 0xd0, 0x95, 0x3d, 0xc3, 0x4a, 0xa8, 0x82, 0xaa, 0xab, 0xad, 0x82, 0xfa, 0x2e,
	0xb1, 0x36, 0x71, 0x31, 0xb1, 0xba, 0xe8, 0x48, 0x2d, 0x3c, 0xa9, 0xf4, 0x6c, 0xc7, 0x21, 0xde,
	0xc8, 0x02, 0x53, 0xf7, 0x32, 0xce, 0x5f, 0xcf, 0x86, 0x25, 0x54, 0xf9, 0x57, 0xcd, 0xb7, 0x3e,
	0x07, 0x8d, 0xa7, 0x1c, 0xfe, 0x9f, 0x08, 0xc9, 0x23, 0xc2, 0x85, 0x4c, 0x42, 0xd2, 0x60, 0x0b,
	0x4b, 0x62, 0x4b, 0xae, 0x35, 0x9b, 0x7f, 0xd2, 0xa4, 0x21, 0x2d, 0x7e, 0xfb, 0xfc, 0xfe, 0x90,
	0xab, 0x91, 0x3d, 0xbe, 0xf8, 0xc7, 0x65, 0xfb, 0x21, 0xf7, 0x08, 0xe7, 0xe7, 0xb7, 0x92, 0xfd,
	0x65, 0x3b, 0xb3, 0x5d, 0x99, 0x07, 0xbf, 0x64, 0x4f, 0xb3, 0x55, 0x93, 0x6c, 0x16, 0xa9, 0xfc,
	0x90, 0x6d, 0x5e, 0xe6, 0xf1, 0xc9, 0xe0, 0x8d, 0x1a, 0x83, 0x11, 0x45, 0xc3, 0x11, 0x45, 0xaf,
	0x23, 0x8a, 0xee, 0xc6, 0xd4, 0x18, 0x8e, 0xa9, 0xf1, 0x32, 0xa6, 0xc6, 0xe5, 0xae, 0x2b, 0x75,
	0x27, 0x6a, 0x33, 0x07, 0xfc, 0xaf, 0x4e, 0x37, 0x73, 0x2f, 0xdd, 0x0f, 0x85, 0x6a, 0xaf, 0x24,
	0x6f, 0xaa, 0xf9, 0x11, 0x00, 0x00, 0xff, 0xff, 0x96, 0x31, 0xc4, 0x00, 0xc3, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// SystemAvailable returns the current system availability flag.
	SystemAvailable(ctx context.Context, in *QuerySystemAvailableRequest, opts ...grpc.CallOption) (*QuerySystemAvailableResponse, error)
	// Whitelist returns the list of authorized addresses.
	Whitelist(ctx context.Context, in *QueryWhitelistRequest, opts ...grpc.CallOption) (*QueryWhitelistResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) SystemAvailable(ctx context.Context, in *QuerySystemAvailableRequest, opts ...grpc.CallOption) (*QuerySystemAvailableResponse, error) {
	out := new(QuerySystemAvailableResponse)
	err := c.cc.Invoke(ctx, "/cosmos.evm.circuit.v1.Query/SystemAvailable", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Whitelist(ctx context.Context, in *QueryWhitelistRequest, opts ...grpc.CallOption) (*QueryWhitelistResponse, error) {
	out := new(QueryWhitelistResponse)
	err := c.cc.Invoke(ctx, "/cosmos.evm.circuit.v1.Query/Whitelist", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// SystemAvailable returns the current system availability flag.
	SystemAvailable(context.Context, *QuerySystemAvailableRequest) (*QuerySystemAvailableResponse, error)
	// Whitelist returns the list of authorized addresses.
	Whitelist(context.Context, *QueryWhitelistRequest) (*QueryWhitelistResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) SystemAvailable(ctx context.Context, req *QuerySystemAvailableRequest) (*QuerySystemAvailableResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SystemAvailable not implemented")
}
func (*UnimplementedQueryServer) Whitelist(ctx context.Context, req *QueryWhitelistRequest) (*QueryWhitelistResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Whitelist not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_SystemAvailable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuerySystemAvailableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).SystemAvailable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cosmos.evm.circuit.v1.Query/SystemAvailable",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).SystemAvailable(ctx, req.(*QuerySystemAvailableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Whitelist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryWhitelistRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Whitelist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cosmos.evm.circuit.v1.Query/Whitelist",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Whitelist(ctx, req.(*QueryWhitelistRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var Query_serviceDesc = _Query_serviceDesc
var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cosmos.evm.circuit.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SystemAvailable",
			Handler:    _Query_SystemAvailable_Handler,
		},
		{
			MethodName: "Whitelist",
			Handler:    _Query_Whitelist_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cosmos/evm/circuit/v1/query.proto",
}

func (m *QuerySystemAvailableRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QuerySystemAvailableRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QuerySystemAvailableRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QuerySystemAvailableResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QuerySystemAvailableResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QuerySystemAvailableResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.SystemAvailable {
		i--
		if m.SystemAvailable {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryWhitelistRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryWhitelistRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryWhitelistRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryWhitelistResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryWhitelistResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryWhitelistResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Whitelist) > 0 {
		for iNdEx := len(m.Whitelist) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Whitelist[iNdEx])
			copy(dAtA[i:], m.Whitelist[iNdEx])
			i = encodeVarintQuery(dAtA, i, uint64(len(m.Whitelist[iNdEx])))
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QuerySystemAvailableRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QuerySystemAvailableResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.SystemAvailable {
		n += 2
	}
	return n
}

func (m *QueryWhitelistRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryWhitelistResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Whitelist) > 0 {
		for _, s := range m.Whitelist {
			l = len(s)
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QuerySystemAvailableRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QuerySystemAvailableRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QuerySystemAvailableRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QuerySystemAvailableResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QuerySystemAvailableResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QuerySystemAvailableResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SystemAvailable", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.SystemAvailable = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryWhitelistRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryWhitelistRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryWhitelistRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryWhitelistResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryWhitelistResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryWhitelistResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Whitelist", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Whitelist = append(m.Whitelist, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
